### ISSUE TITLE
Default Password Issue

### ISSUE THREAD

**Issue by ChrisJones75** [SungardAS/enhanced-snapshots#57]
The default password (EC2 Instance ID) does not seem to work with the new longer form IDs.

**Comment by rabay108** [comment]
Chris - Thanks for notifying about the issue. Can you let us know whether you used the marketplace version or the one from the github and also the instance id that you used for our records.

**Comment by ChrisJones75** [comment]
The AMI we're using is from GitHub: ami-fd838b97. The instance ID for my EC2 instance is similar to: i-0440832b5e2ef4dc2

And thanks for the quick reply. :+1:

**Comment by rabay108** [comment]
Chris - Did you launch it from the market place as the cloud formation stack or used the AMI option? The AMI option requires the IAM role es-admin role created prior to the launching of EC2 instance using AMI. We tested the long instance id a few times and did not encounter the same issue, that's why some insight will be helpful.

**Comment by ChrisJones75** [comment]
We tried the CloudFormation deployment twice with no success, which is why we ended up trying the AMI. We have not created the es-admin role yet, as it was our understanding it was only required to prevent an error within the app configuration.

We'll create the role and let you know the outcome. One more item of note is that our VPC is configured for dedicated instances, but I don't know how that'd affect the instance.

**Comment by rabay108** [comment]
(1) Instance created directly must have an IAM role equivalent of es-admin attached to it before launch otherwise the initialization will fail as it needs to created S3 bucket, DynamoDB tables etc..
(2)  VPC settings do have an impact on the ESS tool.. For eg.: VPCs used for the ess the setting  DNS hostnames: yes (If this setting is NO then the system will fail with the unknown exception); 
(3) catalina.out in the apache-tomcat log files folder will have the actual issue, that will help in troubleshooting the actual issue.

**Comment by ChrisJones75** [comment]
Thanks for your help. Creating the role resolved the login issue. My fault for misinterpreting the intent of it.

As far as VPC settings, we use internal DNS which is setup in our DHCP scope. Will that be sufficient for  this app?

**Comment by rabay108** [comment]
Please check whether you are able to backup and restore volumes successfully. If that looks fine the VPC settings are fine. Otherwise send us a screenshot or text the VPC settings to review.

**Comment by kmcgrath** [comment]
@ChrisJones75 the application runs entirely against the AWS API, so it will need outbound access to the public AWS endpoints (it will not work in a private only subnet).  As long as a public route exists the internal DNS should not interfere with that.

Since the original scope is resolved, I will close this issue.  I would like to know what did not work with the CloudFormation build.  If you have some more data you can provide for that, please open another issue so that we can take a look.
