### ISSUE TITLE
Request: Allow S3 bucket to configurable

### ISSUE THREAD

**Issue by ChrisJones75** [SungardAS/enhanced-snapshots#58]
As a feature request: I'd like to have the ability to change the name of the bucket to be created (for corporate naming standards) and/or use an existing bucket during the Enhanced Snapshot setup.

**Comment by rabay108** [comment]
Chris - In the upcoming version to be released in a few weeks in marketplace and soon on Github, we have the flexibility to some extent but with the prefix "enhancedsnapshots." followed by whatever suffix you can have as well as to use those buckets created for the prior instance. We will login your request for complete flexibility also as a feature change.

**Comment by rabay108** [comment]
Closing this issue as the soon to be released version will have the "enhancedsnapshots." instead of "com.sungardas.enhancedsnapshots." prefix followed by any suffix of choice. We also logged in the bucket facility as part of the CFT as it has an impact on the admin role access needs to allow the user access on that s3 bucket instead of generic s3 bucket access.
