### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by felipaopl** [SungardAS/enhanced-snapshots#60]
Hi devs, first of all, thanks for taking your time here in answering questions and receiving feedback.

This solution looks like exactly what we currently need. Currently, we're paying approx. 40% of our bill just for snapshot storage. We're using CPM to handle snapshot creation / retention but the policy in place is too wide, which leads to a lot of old snapshots adding up to the big numbers monthly.

So, question is: is it possible to use Enhanced Snapshots to just perform the copy procedure to the S3 bucket? Or is the feature tied to snapshots created from ES? We don't want to change our CPM policy (for now) before doing a good amount of testing first.

Also, how the restore actually works? Does ES transfers the snapshot blocks from the S3 bucket to EBS (I know, same thing, but let's pretend we're talking about just the frontend here) and then it just becomes available again in the snapshot list? Also, is it correct to say that the first, real snapshot with all the volume data stays on EBS?

And lastly, if the figure of 20GB/hr is accurate, than a restore job from the S3 bucket to EBS of a snapshot with approx. 120 GB of changed blocks supposedly would take around 6 hours?

Thanks again!

**Comment by rabay108** [comment]
Good to hear your feedback. We have another improvised version coming up soon. 
- Since the volumes could be from any availability zone, a temporal volume is created using snapshot approach and is attached to the ess(enhanced snapshots) instance, then the compressed and deduplicated data is what is moved to S3. 
- While restoring ESS creates a new volume in the availability zone of choice
- Restore process will take shorter time depending on the type of data stored and the compression, de-duplication factors. 
Check this blog out where we did some testing and documented some results based on that
http://blog.sungardas.com/CTOLabs/2016/06/enhanced-snapshots-now-ga-on-the-aws-marketplace/ 

We are also working on improvising the performance considerably at this time and will keep you all posted.

**Comment by felipaopl** [comment]
Thanks for the detailed answers. So my understanding is that I can't select snapshots created manually within EC2 or by other application for S3 bucket archival, correct? Only those created directly with ESS?

**Comment by rabay108** [comment]
@felipaopl Backups can be created only from the volumes and not from the snapshots. Having said that if you create a volume from that snapshot it can be backed up. But not sure that's your need. We can have a feature request made for backing up from snapshots as we do have the back end service components in place and UI must be changed to accommodate that. May be in the future releases. Let know you got answers for all the questions at this point of time.

**Comment by felipaopl** [comment]
Outstanding. Pretty clear, and backing up from the volumes would work just as well for us. Thanks for the detailed explanation.
