### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by NareshDealer** [SungardAS/enhanced-snapshots#95]
Tried to restore from backup and i got this error.

![image](https://cloud.githubusercontent.com/assets/20689530/19007020/411c01e6-8728-11e6-986c-64ac6bb6b37a.png)

Any help is really appreciated. Thanks.

**Comment by NareshDealer** [comment]
Any help is appreciated.

**Comment by iradaik** [comment]
@NareshDealer, I see from the logs that it took to much time to create AWS snapshot, that's why restore task failed.  You can increase time limit for snapshot creation by changing **enhancedsnapshots.wait.time.before.new.sync** property  in **Enhancedsnapshots.properties** file. Please refer to ConfigurationManagement.md document for details. Thanks

**Comment by iradaik** [comment]
@NareshDealer tasks can fail due to temporal AWS issues, currently I see from logs that there was some wrong response from AWS and ESS could not parse it. Please, try to rerun restore task

**Comment by NareshDealer** [comment]
@iradaik Thank you for your response. I have rerun the task but no luck.
![image](https://cloud.githubusercontent.com/assets/20689530/19050693/601f95f4-8975-11e6-9db5-e73e09623b94.png)

**Comment by NareshDealer** [comment]
@iradaik  I have changed the enhancedsnapshots.wait.time.before.new.sync property in Enhancedsnapshots.properties from 5 sec ( i think it was ) to 15mins( 900sec) and it worked with no issues.


Thank you for your help.
